# Generated by Django 5.2.3 on 2025-06-19 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='termo',
            old_name='termo',
            new_name='name',
        ),
        migrations.AddField(
            model_name='termo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='termos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
